config/routes.rb
Autoassist::Application.routes.draw do
  
   
  
  resources :images do
    match '/showimage' => 'images#show_image', :via => [:post, :get], :as => :show_image
    delete 'multiple_delete', :on => :collection
  end
  

  resources :pages

  Mercury::Engine.routes

  devise_for :users

    
    match '/myaccount/' => 'users#show', :as => :profile, :via => :get
    match '/myaccount/update' => 'users#edit', :as => :edit_profile, :via => :put
    
    devise_scope :user do
        get "signup", :to => "devise/registrations#new"
        get "login", :to => "devise/sessions#new"
        delete "logout", :to => "devise/sessions#destroy"
    end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  

    
    resources :articles do
      resources :images do
        match '/add' => 'images#add', :via => :get, :as => :add 
        match '/remove' => 'images#remove', :via => :get, :as => :remove
        match '/thumbnail' => 'images#thumbnail', :via => :get, :as => :thumbnail
      end
      member { post :mercury_update }
    end
    
    scope :articles do
      match ':category/:id' => "articles#show", :as => :category, :via => [:get, :put]
    end
    
    post "/articles/:id", :to => "articles#mercury_update"
    

    

    
    match '/new' => 'pages#new', :as => :new_page, :via => :get
    match '/:id/edit' => 'pages#edit', :as => :edit_page, :via => :get
    match '/:id' => 'pages#show', :as => :page, :via => :get
    match '/:id' => 'pages#update', :via => :put
    match '/:id' => 'pages#destroy', :via => :delete
    
    
    

    
    

    root :to => "pages#home"#, :controller => "articles"

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :images, :dependent => :destroy
    accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true
    
    def thumbnail
        if (self.thumbnail_id != 0) && (!self.thumbnail_id.nil?) then
          @thumb = Image.find(self.thumbnail_id)
          return @thumb.photo.url(:thumbnail)
        else
          return "no-image.jpg"
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < InheritedResources::Base
    
    load_and_authorize_resource
    
    def new
      @article = Article.new
      1.times do
        image = @article.images.build
      end
    end
    
    def index
        @title = "News"
        @article = Article.find(:all, :conditions => {:category => params[:category]})
    end
    
    def create
        @user = current_user
        @articles = @user.articles.create(params[:article])
        redirect_to article_path(@articles)
    end
    
    def mercury_update
        article = Article.find(params[:id])
        article.name = params[:content][:article_title][:value]
        article.content = params[:content][:article_content][:value]
        article.save!
        render :text => ""
    end
    
    def show
      if params[:category].nil?
        @articles = Article.find(params[:id])
      else
        @articles = Article.find(params[:id], :conditions => {:category => params[:category]})
      end
      @title = @articles.category.capitalize
    end
    
    def edit
      @images = Image.find(:all)
      1.times do
        image = @article.images.build
      end  
    end
    
    def update
      @article = Article.find(params[:id])
      if @article.update_attributes(params[:article])
        with_action do |a|
          a.save
          a.remove
          a.any do
            redirect_to :action => 'show', :id => @article
          end
        end
      else
        @subjects = Subject.find(:all)
        render :action => 'edit'
      end
    end
    
    def save
      redirect_to edit_article_image_path(@article.id, @article.thumbnail_id) 
    end
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<script>
$( init );

function init() {
	
	jQuery.ajaxSetup({ 
	  'beforeSend': function(xhr) {xhr.setRequestHeader("Accept", "text/javascript")}
	})

	jQuery.fn.submitWithAjax = function() {
	  this.submit(function() {
	    $.post(this.action, $(this).serialize(), null, "script");
	    return false;
	  })
	  return this;
	};
	
	$("#thumbnail").droppable({
        drop: function( event, ui ) {
            thumbnailImage( ui.draggable );
        }
	});
	
	$("#upload").droppable({
		drop: function( event, ui ) {
			addToGallery( ui.draggable );
		}
	});
}

function addToGallery ($item){
	$.ajax("images/"+$item.attr('id') + "/add");
}


function thumbnailImage ($item) {	
	var $list = $("#thumbnail")
	$list.empty();
	jQuery('#article_thumbnail_id').val($item.attr("id"));
	$.ajax("images/"+ $item.attr('id') + "/thumbnail")
}

function remove_fields(link) {
  $(link).prev("input[type=hidden]").val("1");
  $(link).closest(".draggable").hide();
}

function add_fields(link, association, content) {
  var new_id = new Date().getTime();
  var regexp = new RegExp("new_" + association, "g")
  $(link).parent().before(content.replace(regexp, new_id));
}

</script>

<style>
.draggable { list-style-type: none; margin: 10px; padding: 0; margin-right: 10px; background: #eee; padding: 1px}

#thumbnail { list-style-type: none; margin: 10px; padding: 0; margin-right: 10px; background: #eee; padding: 5px; width: 304px; height:240px}

#upload { height: 150px; width: 150px; background: #eee; padding: 10px; margin: 10px }
</style>

<%= form_for(@article) do |f| %>
	<% if @article.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
			<ul>
				<% @article.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<div id="thumbnail">
		<% unless @article.thumbnail_id.nil? then %>
			<%= image_submit_tag (@article.thumbnail), :name => 'save' %>
		<% else %>
			<%= image_tag "no-image.jpg"%>
		<% end %>
	</div>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</div>

	<div class="field">
		<%= f.label :category %><br />
		<%= f.text_area :category %>
	</div>
	
	<div class="field">
		<%= f.label "Frontpage?" %>
		<%= f.check_box :frontpage %>
	</div>
	
	<div class="field">
		<%= f.label "Visible?" %>
		<%= f.check_box :visible %>
	</div>
	
	<div id="gallery">
	<% for image in @article.images %>
			<% unless image.id.nil? %>
				<%= image_tag image.photo.url(:small), :class => "draggable", :id => image.id %>
				<%= link_to image_tag('delete.png', :width => "15px", :height => "15px"), article_image_remove_path(@article.id, image.id), :remote => true, :class => 'delete_post' %>
			<% end %>
	<% end %>
	</div>
	
	<div id="upload">
		Drop Here to Upload!
	</div>
	
	<%= render 'images/gallery' %>
	
	<!-- <div class="upload">
	<%= f.fields_for :images do |builder| %>
		<%= render 'images/upload', :f => builder%>
	<% end %>
	</div> //-->
	
	<%= f.hidden_field :thumbnail_id %>

	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/articles/_news.html.erb
<section id='slideshow'>
	<ul>
		<% @articles.each do |article| %>
			<article>
    			<header><h1><%= raw article.name.upcase %></h1></header>
            	<%= image_tag article.thumbnail, :width => "302", :height => "240" %>
    			<p><%= article.content %> <%= link_to ("Read More"), category_path(article.category, article.id) %><p>
    		</article>
		<% end %>
	</ul>
    <nav>
    	<a href="#" class="prev"><%= image_tag "slideshow/article_arrow.png", :width => "24", :height => "25" %></a>
    	<a href="#" class="next"><%= image_tag "slideshow/article_arrow.png", :width => "24", :height => "25" %></a>
    </nav>
</section>
<script type="text/javascript">
    $("#slideshow").jCarouselLite({
		auto: 3000,
 		speed: 3000,
        btnNext: ".next",
        btnPrev: ".prev"
    });   
</script>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Frontpage?</th>
    <th>Visible?</th>
	<th></th>
	<% if can? :update, @articles %>
    	<th></th>
		<th></th>
	<% end %>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= link_to (article.name), category_path(article.category, article.id) %></td>
    <td><%= raw article.content %></td>
	<td><%= check_box_tag article.frontpage, article.frontpage, if article.frontpage == true then true end, :disabled => true %></td>
	<td><%= check_box_tag article.visible, article.visible, if article.visible == true then true end, :disabled => true %></td>
	<% if can? :update, @articles %>
    	<td><%= link_to 'Edit', edit_article_path(article) %></td>
    	<td><%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %></td>
	<% end %>
  </tr>
<% end %>
</table>

<br />

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <div id="article_title" class="mercury-region" data-type="editable">
  <%= raw @article.name %>
  </div>
</p>

<p>
  <b>Content:</b>
  <div id="article_content" class="mercury-region" data-type="editable">
  	<%= raw @article.content %>
	</div>
</p>

<p>
  <b>Category:</b>
  <%= @article.category %>
</p>

<p>Thumbnail!</p>
<%= image_tag @article.thumbnail %>


<% for image in @article.images %>
	<div id='cropwrap'>
  		<%= image_tag image.photo.url(:medium), :id => 'cropimage' %>	
	</div>
<% end %>

<%= link_to "Edit", "/editor" + request.path, :id => "edit_link", :data => {:save_url => mercury_update_article_path(@article)} %>
<%= link_to 'Back', articles_path %>