config/routes.rb
Autoassist::Application.routes.draw do
  
   
  
  resources :images do
    match '/showimage' => 'images#show_image', :via => [:post, :get], :as => :show_image
    delete 'multiple_delete', :on => :collection
  end
  

  resources :pages

  Mercury::Engine.routes

  devise_for :users

    
    match '/myaccount/' => 'users#show', :as => :profile, :via => :get
    match '/myaccount/update' => 'users#edit', :as => :edit_profile, :via => :put
    
    devise_scope :user do
        get "signup", :to => "devise/registrations#new"
        get "login", :to => "devise/sessions#new"
        delete "logout", :to => "devise/sessions#destroy"
    end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  

    
    resources :articles do
      resources :images do
        match '/add' => 'images#add', :via => :get, :as => :add 
        match '/remove' => 'images#remove', :via => :get, :as => :remove
        match '/thumbnail' => 'images#thumbnail', :via => :get, :as => :thumbnail
      end
      member { post :mercury_update }
    end
    
    scope :articles do
      match ':category/:id' => "articles#show", :as => :category, :via => [:get, :put]
    end
    
    post "/articles/:id", :to => "articles#mercury_update"
    

    

    
    match '/new' => 'pages#new', :as => :new_page, :via => :get
    match '/:id/edit' => 'pages#edit', :as => :edit_page, :via => :get
    match '/:id' => 'pages#show', :as => :page, :via => :get
    match '/:id' => 'pages#update', :via => :put
    match '/:id' => 'pages#destroy', :via => :delete
    
    
    

    
    

    root :to => "pages#home"#, :controller => "articles"

end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.collection_select :parent_id, Page.all(:order => "title"), :id, :title, :include_blank => true %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/home.html.erb
<section id='feature'>
		<%= image_tag "feature/Fiat-500-US-Spec-02.jpg", :width => "990", :height => "420" %>
		<%= image_tag "feature/Fiat-500-Convertible-2.jpg", :width => "990", :height => "420" %>
		<%= image_tag "feature/2010_fiat_500_actprf_ns_31610_717.jpg", :width => "990", :height => "420" %>
</section>

<%= render "articles/news" %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.content %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>