config/routes.rb
Autoassist::Application.routes.draw do
  
   
  
  resources :images do
    match '/showimage' => 'images#show_image', :via => [:post, :get], :as => :show_image
    delete 'multiple_delete', :on => :collection
  end
  

  resources :pages

  Mercury::Engine.routes

  devise_for :users

    
    match '/myaccount/' => 'users#show', :as => :profile, :via => :get
    match '/myaccount/update' => 'users#edit', :as => :edit_profile, :via => :put
    
    devise_scope :user do
        get "signup", :to => "devise/registrations#new"
        get "login", :to => "devise/sessions#new"
        delete "logout", :to => "devise/sessions#destroy"
    end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  

    
    resources :articles do
      resources :images do
        match '/add' => 'images#add', :via => :get, :as => :add 
        match '/remove' => 'images#remove', :via => :get, :as => :remove
        match '/thumbnail' => 'images#thumbnail', :via => :get, :as => :thumbnail
      end
      member { post :mercury_update }
    end
    
    scope :articles do
      match ':category/:id' => "articles#show", :as => :category, :via => [:get, :put]
    end
    
    post "/articles/:id", :to => "articles#mercury_update"
    

    

    
    match '/new' => 'pages#new', :as => :new_page, :via => :get
    match '/:id/edit' => 'pages#edit', :as => :edit_page, :via => :get
    match '/:id' => 'pages#show', :as => :page, :via => :get
    match '/:id' => 'pages#update', :via => :put
    match '/:id' => 'pages#destroy', :via => :delete
    
    
    

    
    

    root :to => "pages#home"#, :controller => "articles"

end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    has_many :images, :dependent => :destroy
    accepts_nested_attributes_for :images, :reject_if => :all_blank, :allow_destroy => true
    
    def thumbnail
        if (self.thumbnail_id != 0) && (!self.thumbnail_id.nil?) then
          @thumb = Image.find(self.thumbnail_id)
          return @thumb.photo.url(:thumbnail)
        else
          return "no-image.jpg"
        end
    end
end

app/models/image.rb
class Image < ActiveRecord::Base
  
  belongs_to :articles
  acts_as_list
  has_attached_file :photo, :styles => { :thumbnail => "302x240>", :small => "150x150>", :medium => "300x300>" }
  
  def self.thumbnail_by_id(id)
    image = find_by_id(id)
    return "no-image.jpg" if image.nil
    return image.photo.url(:thumbnail)
  end
  
  def to_jq_upload
      {
        "name" => self.photo_file_name,
        "id" => self.id,
        "size" => self.photo_file_size,
        "url" => self.photo.url(:small),
        "thumbnail_url" => self.photo.url(:thumbnail),
        "delete_url" => nil,
        "delete_type" => "DELETE" 
      }
    end
end

app/controllers/images_controller.rb
class ImagesController < InheritedResources::Base
  
  require 'json'
  
  def index
    @images = Image.all
    #@upload = Image.new
    respond_to do |format|
      format.html
      format.json {render :json => @images.collect { |p| p.to_jq_upload }.to_json}
    end
  end
  
  def show
    @images = Image.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @images.as_json }
    end
  end
  
  def create
    @images = Image.new(params[:image])
      if @images.save
          render :json => @images.to_jq_upload.as_json
      else
          @images = Image.all
          render :action => 'index'
      end
   end
  
  def destroy
    image = Image.find(params[:id])
    if image.article_id != nil then
      article = Article.find(image.article_id)
      article.thumbnail_id = nil
      article.save
    end
    image.destroy
    respond_to do |format|
      format.js { render :js => "removeItem(" + params[:id] + ")"}
    end
  end
  
  def update
    @images = Image.find(params[:id])
    crop_params = "#{params[:w]}x#{params[:h]}+#{params[:x]}+#{params[:y]}"
    resize_params = "304x240"  

    imageCommand = Thread.new do
      image = MiniMagick::Image.open(@images.photo.path)
      image.crop(crop_params)
      image.thumbnail(resize_params)
      image.write(@images.photo.path(:thumbnail))
    end
    imageCommand.join
    redirect_to edit_article_path(@images.article_id)
  end
  
  def show_image
    @image = Image.find(params[:image_id])
    respond_to do |format|
      format.js
    end
  end
  
  def thumbnail
    @image = Image.find(params[:image_id])
    respond_to do |format|
      format.html { redirect_to edit_article_path(params[:article_id]) }
      format.js
    end
  end
  
  def remove
    @image = Image.find(params[:image_id])
    @image.article_id = nil
    @image.save
    respond_to do |format|
      format.html { redirect_to edit_article_path(params[:article_id]) }
      format.js 
    end
  end
  
  def add
    @image = Image.find(params[:image_id])
    @image.article_id = params[:article_id]
    @image.save
    respond_to do |format|
      format.html { redirect_to edit_article_path(params[:article_id])}
      format.js
    end
  end
  
  def multiple_delete
    @images = Image.find(params[:image_ids])
    @images.each do |image|
      if image.article_id != nil then
        article = Article.find(image.article_id)
        article.thumbnail_id = nil
        article.save
      end
      image.destroy
    end
    #respond_to do |format|
    #  format.js { render :js => "removeItem(" + params[:id] + ")"}
    #end
    redirect_to images_path
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br />
    <%= f.number_field :article_id %>
  </div>

	<div class="field">
		<%= f.file_field :photo %>
	</div>
  
  	<div class="actions">
    	<%= f.submit %>
  	</div>
<% end %>

app/views/images/_gallery.html.erb
<%= stylesheet_link_tag "images" %>
<section id='images_slideshow'>
	<ul>
		<% @images.each do |image| %>
			<article>
				<%= image_tag image.photo.url(:small), :id => image.id, :class => "draggable" %>
				<p>
					<%= link_to 'Show', image %>
					<%= link_to 'Edit', edit_image_path(image) %>
					<%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete %>
				</p>
			</article>
		<% end %>
	</ul>
	<nav>
		<a href="#" class="next"><%= image_tag "slideshow/article_arrow.png", :width => "24", :height => "25" %></a>
		<a href="#" class="prev"><%= image_tag "slideshow/article_arrow.png", :width => "24", :height => "25" %></a>
	</nav>
</section>
<script type="text/javascript">
    $("#images_slideshow").jCarouselLite({
 		speed: 1000,
		visible: 5,
        btnNext: ".next",
        btnPrev: ".prev",
		scroll: 5
    });   
</script>

app/views/images/_photo_edit.html.erb
<%= javascript_include_tag "jquery.Jcrop" %>
<%= stylesheet_link_tag "jquery.jcrop" %>
<script type="text/javascript" language="JavaScript">
jQuery(function() {
	$('#target').Jcrop({
   		aspectRatio : 1.25,
		onSelect : updateCoords
	});
});

function updateCoords(c)
{
    jQuery('#x').val(c.x);
    jQuery('#y').val(c.y);
    jQuery('#w').val(c.w);
    jQuery('#h').val(c.h);
};

function updatePreview() {
    if(parseInt(jQuery("#w").val()) > 0) {
        // Show image preview
        var imageObj = $("#target")[0];
        var canvas = $("#preview")[0];
        var context = canvas.getContext("2d");
        context.drawImage(imageObj, jQuery('#x').val(), jQuery('#y').val(), jQuery('#w').val(), jQuery('#h').val(), 0, 0, canvas.width, canvas.height);
    }
	else {
		alert('Please select a crop region then press submit.');
	}
};

$(document).ready(function() {
    $('#preview_btn').click(function() {
        updatePreview();
    });
});


</script>

<h1>Editing Images</h1>
 
<!-- CROP FORM -->
<%= form_for(@image) do |f| %>
	<% if @image.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
			<ul>
				<% @image.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<input type="hidden" id="x" name="x" />
	<input type="hidden" id="y" name="y" />
	<input type="hidden" id="w" name="w" />
	<input type="hidden" id="h" name="h" />
	
	<div>
		<%= image_tag @image.photo.url(:original), :id => "target" %>
	</div>
	<div>
		<canvas id="preview" style="width:304px;height:240px;overflow:hidden;">
	</div>
	
	<input type="button" id="preview_btn" value="Preview" /> 
	
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/images/_table.html.erb
<%= stylesheet_link_tag "jquery-ui-1.8.19.custom" %>

<style>
#gallery{
	position: relative;
	width: 990px;
	height: 325px;
	overflow-y: scroll;
}
.image{
	padding: 5px;
	height: 170px;
	width: 150px;
	float: left;
}

#fileupload-progress{
	position: absolute;
	left: -5px;
	top: 65px;
	width: 163px;
	height: 20px;
	border: none;
}

#fileupload-box {
	position: relative;
	height: 148px;
	border: thin dotted #CCC;
	width: 148px;
}
</style>
<%= form_for Image.new, :html => { :multipart => true, :id => "fileupload", :remote => true  } do |f| %>
<section id="gallery">
	<div id="fileupload-box" class="image">
		<div id="fileupload-progress">
			<%= f.file_field :photo, :id => 'fileupload-field' %>
		</div>
	</div>
<% end %>
<%= form_tag multiple_delete_images_path, :method => :delete do %>
	<% @images.each do |image| %>
		<div class="image">
			<%= image_tag image.photo.url(:small), :id => image.id, :class => "draggable" %>
			<div float="clear">
			<%= check_box_tag "image_ids[]", image.id %>
			<%= link_to 'Show', image %>
			<%= link_to 'Edit', edit_image_path(image) %>
			<%= link_to 'Destroy', image, :remote => true, :confirm => 'Are you sure?', :method => :delete %>
			</div>
		</div>
	<% end %>
	</section>
	<%= submit_tag "Remove Images" %>
<% end %>

	<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
	<%= javascript_include_tag 'jquery.iframe-transport.js' %>
	<%= javascript_include_tag 'jquery.fileupload.js' %>
	<%= javascript_include_tag 'jquery.fileupload-ui.js' %>

	<script type="text/javascript" charset="utf-8">
		function removeItem (id) {
			$('div.image').find('img#' + id ).parent().fadeOut("slow", function () {
				this.remove();
			});
		};
	
	    $(function ($) {
		
			jQuery.ajaxSetup({ 
			  'beforeSend': function(xhr) {xhr.setRequestHeader("Accept", "text/javascript")}
			})

			jQuery.fn.submitWithAjax = function() {
			  this.submit(function() {
			    $.post(this.action, $(this).serialize(), null, "script");
			    return false;
			  })
			  return this;
			};
			
			$('#fileupload').fileupload({
				autoUpload: true,
				done: function(e, data) {
					$.ajax('images/' + data.result.id + '/showimage');
					$("fileupload-progress").remove();
					$('input#fileupload-field').show();
				},
				start: function(e,data) {
					$('input#fileupload-field').hide();
					$("#fileupload-status").append("<div id='fileupload-progress'></div>").html();
				},
				progress: function(e,data) {
					var progress = parseInt(data.loaded/data.total * 100, 10)
					$("#fileupload-progress").progressbar({
						value: progress
					});
				}
			});
	    });
	</script>

app/views/images/_upload.html.erb
<div class="field">
	<%= f.file_field :photo %>
</div>

app/views/images/add.js.erb
var gallery = $("#gallery");
gallery.fadeIn('slow', function() {
	gallery.append("<%= escape_javascript(image_tag @image.photo.url(:small), :class => 'draggable ui-draggable', :id => @image.id) %>");
	gallery.append("<%= escape_javascript(link_to image_tag('delete.png', :width => '15px', :height => '15px'), article_image_remove_path(@image.article_id, @image.id), :remote => true, :class => 'delete_post') %>");
});

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'photo_edit' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', edit_article_path(params[:article_id]) %>

app/views/images/index.html.erb
<h1>Listing images</h1>
<%= render 'table' %>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/remove.js.erb
var image = $("#<%=h @image.id %>");
image.fadeOut('slow', function() {
	image.remove();
});

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Article:</b>
  <%= @image.article_id %>
</p>

<p>
	<b>Photo:</b>
	<%= image_tag @image.photo.url(:thumbnail) %>
</p>


<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/images/show_image.js.erb
var gallery = $("div.image").first();
gallery.fadeIn("slow", function() {
	$('<div class="image"><%= escape_javascript(image_tag @image.photo.url(:small), :id => @image.id, :class => "draggable") %> \
	<%= escape_javascript(link_to 'Show', @image) %> \
	<%= escape_javascript(link_to 'Edit', edit_image_path(@image)) %> \
	<%= escape_javascript(link_to 'Destroy', @image, :remote => true, :confirm => 'Are you sure?', :method => :delete) %></div>').insertAfter(this);
});

app/views/images/thumbnail.js.erb
$("#thumbnail").append("<%= escape_javascript(image_submit_tag (@image.photo.url(:thumbnail)), :name => 'save') %>");