config/routes.rb
Autoassist::Application.routes.draw do
  
   
  
  resources :images do
    match '/showimage' => 'images#show_image', :via => [:post, :get], :as => :show_image
    delete 'multiple_delete', :on => :collection
  end
  

  resources :pages

  Mercury::Engine.routes

  devise_for :users

    
    match '/myaccount/' => 'users#show', :as => :profile, :via => :get
    match '/myaccount/update' => 'users#edit', :as => :edit_profile, :via => :put
    
    devise_scope :user do
        get "signup", :to => "devise/registrations#new"
        get "login", :to => "devise/sessions#new"
        delete "logout", :to => "devise/sessions#destroy"
    end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  
  

    
    resources :articles do
      resources :images do
        match '/add' => 'images#add', :via => :get, :as => :add 
        match '/remove' => 'images#remove', :via => :get, :as => :remove
        match '/thumbnail' => 'images#thumbnail', :via => :get, :as => :thumbnail
      end
      member { post :mercury_update }
    end
    
    scope :articles do
      match ':category/:id' => "articles#show", :as => :category, :via => [:get, :put]
    end
    
    post "/articles/:id", :to => "articles#mercury_update"
    

    

    
    match '/new' => 'pages#new', :as => :new_page, :via => :get
    match '/:id/edit' => 'pages#edit', :as => :edit_page, :via => :get
    match '/:id' => 'pages#show', :as => :page, :via => :get
    match '/:id' => 'pages#update', :via => :put
    match '/:id' => 'pages#destroy', :via => :delete
    
    
    

    
    

    root :to => "pages#home"#, :controller => "articles"

end

app/views/layouts/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul> 
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	<nav>
		<ul>
			<li><%= link_to "Home", root_path %> | </li>
			<li><%= link_to "News", articles_path %> | </li>
			<% Page.roots.each do |page, index| %>
				<% if Page.roots.last == page or Page.roots.first == page then %>
					<li><%= link_to h(page.title), page %></li>
				<% else %>
					<li><%= link_to h(page.title), page %> | </li>
				<% end %>
			<% end %>
		</ul>
    </nav>
    <section>
	<% if can? :update, @article %>
		<p><%= link_to 'New Article', new_article_path %> | <%= link_to 'New Page', new_page_path %></p>
	<% end %>
    <p>For business inquiries please email inquiries@autoassistant.com</p>
    <p><small>2012 © Auto Assistant</small></p>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= image_tag "header_logo.png" %>
	<section>
		<% if user_signed_in? %>
			<li><%= link_to "My Account", profile_path %></li>
			<li><%= link_to "Sign Out", logout_path, :method => :delete %></li>
		<% else %>
			<li><%= link_to "Sign Up", signup_path %></li>
			<li><%= link_to "Sign In", login_path %></li>
		<% end %>
	</section>
	<nav>
		<ul id="navbar">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "News", articles_path %></li>
			<% Page.roots.each do |page, index| %>
				<li><%= link_to h(page.title), page %>
				<% if page.has_children? %>
					<ul class='submenu'>
					<% for child in page.children %>
						<li><%= link_to h(child.title), child %></li>
					<% end %>
					</ul>
				<% end %>
				</li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="no">
<head>
	<title><%= title %></title>
	<%= stylesheet_link_tag "application" %>
	<%= javascript_include_tag :application %>
	<%= csrf_meta_tag %>
	

	<script type="text/javascript" src="http://malsup.github.com/chili-1.7.pack.js"></script>
	<script type="text/javascript" src="http://malsup.github.com/jquery.cycle.all.js"></script>
	<script type="text/javascript" src="http://malsup.github.com/jquery.easing.1.3.js"></script>

	<%= javascript_include_tag "jcarousellite_1.0.1" %>

	<script type="text/javascript">

	$(document).ready(function(){

		$mainmenu = $('ul#navbar');
		$submenu = $('ul#navbar li:has("ul")');

		//Find the length of the navbar
		var menuItems = ($("ul#navbar a").length - $("ul#navbar li ul a").length);

		//Find the number of elements in the main menu
		var totalwidth = 0;

		//Calculate the total width of each element
		$('ul#navbar li').each(function(){
			totalwidth += $(this).width();					
		});


		//Calculate the required padding
		var requiredPadding = Math.floor(($mainmenu.width() - totalwidth)/(menuItems) / 2);

		var roundingErrorFix = $mainmenu.width()-((requiredPadding*menuItems*2)+totalwidth);

		$('ul#navbar li a').each(function(i) {
	    if(i==0) {
	        $(this).css('padding-left',requiredPadding+roundingErrorFix/2+'px')
	            .css('padding-right',requiredPadding+roundingErrorFix/2+'px');
	    }
	    else {
	        $(this).css('padding-left',requiredPadding+'px')
	            .css('padding-right',requiredPadding+'px');
	    	}
		});

		$submenu.each(function(){
			// Find difference between main menu and sub menu width
			// Add difference to submenu width
			$(this).find('.submenu').css('width',$(this).outerWidth(true)+'px');
		})

		//$("#feature").css("overflow", "hidden");
	    $("#feature-nav").css("visibility", "visible");
	    $("#feature-nav a[href=#1]").addClass("active");

		$('#feature').after('<nav id="feature-nav">').cycle({
	        fx: 'fade', // choose your transition type, ex: fade, scrollUp, shuffle, etc...
			speed: 3000,
			timeout: 3000,
			pager: '#feature-nav',
			before: function() { if (window.console) console.log(this.src); }
	    });

	    $("#feature-nav a").click(function(){
	        $("#feature-nav a").removeClass("activeSlide");
	        $(this).addClass("activeSlide");

	    });
	});
</script>

</head>
<body>
	<%= render 'layouts/header' %>
		<section>
			<%= yield %>
		</section>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury', 'mercury_overrides' %>
  </head>
  <body>
    <script type="text/javascript">
      var saveUrl = null; // Set to the url that you want to save any given page to.
      var options = {
        saveStyle: 'form',  // 'form', or 'json' (default json)
        saveMethod: null, // 'POST', or 'PUT', (create, vs. update -- default POST)
        visible: null     // if the interface should start visible or not (default true)
      };

      <!-- Mix in any configurations provided through Rails.application.config.mercury_config -->
      <% if Rails.application.config.respond_to?(:mercury_config) %>
        jQuery.extend(Mercury.config, <%= Rails.application.config.mercury_config.to_json.html_safe %>);
      <% end -%>

      <!-- Mix in any options for PageEditor provided through Rails.application.config.mercury_page_editor_config -->
      <% if Rails.application.config.respond_to?(:mercury_page_editor_config) %>
        jQuery.extend(options, <%= Rails.application.config.mercury_page_editor_config.to_json.html_safe %>);
      <% end -%>

      <!-- Instantiate the PageEditor -->
      new Mercury.PageEditor(saveUrl, options);
    </script>
  </body>
</html>